### ISSUE TITLE
Requiring Directories with mustache 

### ISSUE THREAD

**Issue by PublicAutopsy** [TiddoLangerak/mu2Express#2]
Im not sure if this is an issue you are able to fix or maybe its more of an issue with mu2 but when I try and include a directory with mustache on the client side, it breaks the entire site. 

Also I just want to thank you for this project cause I really enjoy using it

**Comment by TiddoLangerak** [comment]
First of all sorry that I didn't reply earlier, I simply didn't notice this issue until I received the message that you closed the issue. Is your issue still an issue? Also, I don't really understand what the exact issue is. If you still want this issue to be resolved, could you post some example code?

I'm glad you enjoy this project!

**Comment by PublicAutopsy** [comment]
No worries man, I was just trying to use partials and they would break the entire site, causing a 500 to be thrown. When I was digging I found it to be a problem of mu2 and not with your code. I switched to using mmm because its virtually the same as your project but supports partials. I still do like this project and would love to see this issue fixed
